"""add_people_assets_table

Revision ID: 112235f885a5
Revises: d75fd19f4090
Create Date: 2026-06-23 09:46:45.703742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '112235f885a5'
down_revision: Union[str, None] = 'd75fd19f4090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('manager', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_assets_asset_type'), 'people_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_people_assets_department'), 'people_assets', ['department'], unique=False)
    op.create_index(op.f('ix_people_assets_email'), 'people_assets', ['email'], unique=False)
    op.create_index(op.f('ix_people_assets_organization_id'), 'people_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_people_assets_status'), 'people_assets', ['status'], unique=False)
    op.drop_index('ix_support_access_requests_approved_by', table_name='support_access_requests')
    op.drop_index('ix_support_access_requests_organization_id', table_name='support_access_requests')
    op.drop_index('ix_support_access_requests_platform_user_id', table_name='support_access_requests')
    op.drop_index('ix_support_access_requests_requested_by', table_name='support_access_requests')
    op.drop_index('ix_support_access_requests_resolved_by', table_name='support_access_requests')
    op.drop_table('support_access_requests')
    op.alter_column('controls', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('specified', 'in_draft', 'done', 'compliant', 'non_compliant', 'in_progress', 'not_applicable', name='compliance_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controls', 'status',
               existing_type=sa.Enum('specified', 'in_draft', 'done', 'compliant', 'non_compliant', 'in_progress', 'not_applicable', name='compliance_status', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.create_table('support_access_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('access_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='support_access_requests_approved_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='support_access_requests_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], name='support_access_requests_platform_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='support_access_requests_requested_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['platform_users.id'], name='support_access_requests_resolved_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='support_access_requests_pkey')
    )
    op.create_index('ix_support_access_requests_resolved_by', 'support_access_requests', ['resolved_by'], unique=False)
    op.create_index('ix_support_access_requests_requested_by', 'support_access_requests', ['requested_by'], unique=False)
    op.create_index('ix_support_access_requests_platform_user_id', 'support_access_requests', ['platform_user_id'], unique=False)
    op.create_index('ix_support_access_requests_organization_id', 'support_access_requests', ['organization_id'], unique=False)
    op.create_index('ix_support_access_requests_approved_by', 'support_access_requests', ['approved_by'], unique=False)
    op.drop_index(op.f('ix_people_assets_status'), table_name='people_assets')
    op.drop_index(op.f('ix_people_assets_organization_id'), table_name='people_assets')
    op.drop_index(op.f('ix_people_assets_email'), table_name='people_assets')
    op.drop_index(op.f('ix_people_assets_department'), table_name='people_assets')
    op.drop_index(op.f('ix_people_assets_asset_type'), table_name='people_assets')
    op.drop_table('people_assets')
    # ### end Alembic commands ###
