"""Add fields and unique constraint to canonical_assets

Revision ID: 16c3a136dc2c
Revises: 1bb1919ee29f
Create Date: 2026-07-16 18:10:25.076379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c3a136dc2c'
down_revision: Union[str, None] = '1bb1919ee29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_assets', sa.Column('environment', sa.String(length=50), nullable=True))
    op.add_column('canonical_assets', sa.Column('data_classification', sa.String(length=50), nullable=True))
    op.add_column('canonical_assets', sa.Column('source_connection_id', sa.String(length=255), nullable=True))
    op.add_column('canonical_assets', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('canonical_assets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_canonical_assets_source_connection_id'), 'canonical_assets', ['source_connection_id'], unique=False)
    op.create_unique_constraint('uq_asset_per_provider', 'canonical_assets', ['organization_id', 'provider', 'provider_resource_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_per_provider', 'canonical_assets', type_='unique')
    op.drop_index(op.f('ix_canonical_assets_source_connection_id'), table_name='canonical_assets')
    op.drop_column('canonical_assets', 'deleted_at')
    op.drop_column('canonical_assets', 'last_seen_at')
    op.drop_column('canonical_assets', 'source_connection_id')
    op.drop_column('canonical_assets', 'data_classification')
    op.drop_column('canonical_assets', 'environment')
    # ### end Alembic commands ###
