"""Add canonical asset models

Revision ID: 1bb1919ee29f
Revises: efe87bddac51
Create Date: 2026-07-15 20:32:07.188974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb1919ee29f'
down_revision: Union[str, None] = 'efe87bddac51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=1024), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_resources_account_id'), 'raw_resources', ['account_id'], unique=False)
    op.create_index(op.f('ix_raw_resources_organization_id'), 'raw_resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_raw_resources_provider'), 'raw_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_raw_resources_resource_id'), 'raw_resources', ['resource_id'], unique=False)
    op.create_table('canonical_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('aws', 'azure', 'gcp', 'okta', 'github', 'crowdstrike', 'intune', 'manual', 'other', name='provider_enum', native_enum=False), nullable=False),
    sa.Column('provider_resource_id', sa.String(length=1024), nullable=False),
    sa.Column('canonical_type', sa.Enum('identity', 'group', 'role', 'service_account', 'authentication_policy', 'compute', 'serverless', 'container', 'container_registry', 'storage', 'database', 'data_warehouse', 'cache', 'backup', 'network', 'firewall', 'load_balancer', 'dns', 'vpn', 'secret', 'certificate', 'encryption_key', 'logging', 'monitoring', 'threat_finding', 'vulnerability', 'compliance_finding', 'application', 'repository', 'pipeline', 'deployment', 'artifact', 'webhook', 'device', 'mobile_device', 'endpoint_protection', 'employee', 'background_check', 'security_training', 'policy_acknowledgement', 'vendor', 'vendor_assessment', 'nda', 'ticket', 'other', name='canonical_type_enum', native_enum=False), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('raw_resource_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_resource_id'], ['raw_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_assets_account_id'), 'canonical_assets', ['account_id'], unique=False)
    op.create_index(op.f('ix_canonical_assets_canonical_type'), 'canonical_assets', ['canonical_type'], unique=False)
    op.create_index(op.f('ix_canonical_assets_organization_id'), 'canonical_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_canonical_assets_provider'), 'canonical_assets', ['provider'], unique=False)
    op.create_index(op.f('ix_canonical_assets_raw_resource_id'), 'canonical_assets', ['raw_resource_id'], unique=False)
    op.create_table('asset_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('target_asset_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('uses', 'attached_to', 'belongs_to', 'inside', 'encrypted_by', 'member_of', 'manages', 'depends_on', 'connects_to', 'routes_to', 'logs_to', 'monitors', 'protects', 'contains', 'deployed_by', 'runs_on', 'associated_with', name='relationship_type_enum', native_enum=False), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['canonical_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['canonical_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_relationships_organization_id'), 'asset_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_relationship_type'), 'asset_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_asset_relationships_source_asset_id'), 'asset_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_target_asset_id'), 'asset_relationships', ['target_asset_id'], unique=False)
    op.alter_column('permissions', 'action',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('view', 'create', 'edit', 'delete', 'approve', 'bulk_import', 'map', 'acknowledge', 'upload', 'export', 'configure', 'resolve', 'plan', 'conduct', 'findings', 'remediate', 'close', 'score', 'treat', 'upload_docs', 'manage_templates', 'manage_answers', 'respond', name='permission_action', native_enum=False),
               existing_nullable=False)
    op.alter_column('sso_configurations', 'provider',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SAML', 'OIDC', 'Google', 'Azure', 'Microsoft', name='sso_provider', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'sso_provider',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('SAML', 'OIDC', 'Google', 'Azure', 'Microsoft', name='sso_provider', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sso_provider',
               existing_type=sa.Enum('SAML', 'OIDC', 'Google', 'Azure', 'Microsoft', name='sso_provider', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('sso_configurations', 'provider',
               existing_type=sa.Enum('SAML', 'OIDC', 'Google', 'Azure', 'Microsoft', name='sso_provider', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('permissions', 'action',
               existing_type=sa.Enum('view', 'create', 'edit', 'delete', 'approve', 'bulk_import', 'map', 'acknowledge', 'upload', 'export', 'configure', 'resolve', 'plan', 'conduct', 'findings', 'remediate', 'close', 'score', 'treat', 'upload_docs', 'manage_templates', 'manage_answers', 'respond', name='permission_action', native_enum=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_asset_relationships_target_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_source_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_relationship_type'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_organization_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_canonical_assets_raw_resource_id'), table_name='canonical_assets')
    op.drop_index(op.f('ix_canonical_assets_provider'), table_name='canonical_assets')
    op.drop_index(op.f('ix_canonical_assets_organization_id'), table_name='canonical_assets')
    op.drop_index(op.f('ix_canonical_assets_canonical_type'), table_name='canonical_assets')
    op.drop_index(op.f('ix_canonical_assets_account_id'), table_name='canonical_assets')
    op.drop_table('canonical_assets')
    op.drop_index(op.f('ix_raw_resources_resource_id'), table_name='raw_resources')
    op.drop_index(op.f('ix_raw_resources_provider'), table_name='raw_resources')
    op.drop_index(op.f('ix_raw_resources_organization_id'), table_name='raw_resources')
    op.drop_index(op.f('ix_raw_resources_account_id'), table_name='raw_resources')
    op.drop_table('raw_resources')
    # ### end Alembic commands ###
