"""Add last_access_review to people_assets

Revision ID: 1de22833a787
Revises: f2c099daca39
Create Date: 2026-06-29 10:00:46.432550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de22833a787'
down_revision: Union[str, None] = 'f2c099daca39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_assets', sa.Column('last_access_review', sa.DateTime(timezone=True), nullable=True))
    op.add_column('people_assets', sa.Column('last_reviewed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people_assets', 'users', ['last_reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people_assets', type_='foreignkey')
    op.drop_column('people_assets', 'last_reviewed_by')
    op.drop_column('people_assets', 'last_access_review')
    # ### end Alembic commands ###
