"""add_asset_owner_to_people_assets

Revision ID: 3df19addf042
Revises: 112235f885a5
Create Date: 2026-06-23 12:09:12.978656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df19addf042'
down_revision: Union[str, None] = '112235f885a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_assets', sa.Column('asset_owner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people_assets', 'asset_owner')
    # ### end Alembic commands ###
