"""add endpoint_devices table

Revision ID: 6c12b4a43d2f
Revises: 3df19addf042
Create Date: 2026-06-23 12:36:52.236437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c12b4a43d2f'
down_revision: Union[str, None] = '3df19addf042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['people_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_devices_asset_type'), 'endpoint_devices', ['asset_type'], unique=False)
    op.create_index(op.f('ix_endpoint_devices_assigned_to'), 'endpoint_devices', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_endpoint_devices_department'), 'endpoint_devices', ['department'], unique=False)
    op.create_index(op.f('ix_endpoint_devices_organization_id'), 'endpoint_devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_endpoint_devices_serial_number'), 'endpoint_devices', ['serial_number'], unique=False)
    op.create_index(op.f('ix_endpoint_devices_status'), 'endpoint_devices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_devices_status'), table_name='endpoint_devices')
    op.drop_index(op.f('ix_endpoint_devices_serial_number'), table_name='endpoint_devices')
    op.drop_index(op.f('ix_endpoint_devices_organization_id'), table_name='endpoint_devices')
    op.drop_index(op.f('ix_endpoint_devices_department'), table_name='endpoint_devices')
    op.drop_index(op.f('ix_endpoint_devices_assigned_to'), table_name='endpoint_devices')
    op.drop_index(op.f('ix_endpoint_devices_asset_type'), table_name='endpoint_devices')
    op.drop_table('endpoint_devices')
    # ### end Alembic commands ###
