"""add_overlook_module

Revision ID: 8e9ffc5f42bd
Revises: b7ea051b0d4a
Create Date: 2026-06-07 17:13:38.707758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e9ffc5f42bd'
down_revision: Union[str, None] = 'b7ea051b0d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_permissions_action'), 'platform_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_platform_permissions_name'), 'platform_permissions', ['name'], unique=True)
    op.create_index(op.f('ix_platform_permissions_resource'), 'platform_permissions', ['resource'], unique=False)
    op.create_table('platform_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_roles_name'), 'platform_roles', ['name'], unique=True)
    op.create_table('platform_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_table('platform_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_logs_platform_user_id'), 'platform_audit_logs', ['platform_user_id'], unique=False)
    op.create_table('platform_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['platform_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['platform_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('platform_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['platform_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('support_access_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'revoked', name='support_access_status', native_enum=False), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('access_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_access_requests_approved_by'), 'support_access_requests', ['approved_by'], unique=False)
    op.create_index(op.f('ix_support_access_requests_organization_id'), 'support_access_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_access_requests_platform_user_id'), 'support_access_requests', ['platform_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_access_requests_platform_user_id'), table_name='support_access_requests')
    op.drop_index(op.f('ix_support_access_requests_organization_id'), table_name='support_access_requests')
    op.drop_index(op.f('ix_support_access_requests_approved_by'), table_name='support_access_requests')
    op.drop_table('support_access_requests')
    op.drop_table('platform_user_roles')
    op.drop_table('platform_role_permissions')
    op.drop_index(op.f('ix_platform_audit_logs_platform_user_id'), table_name='platform_audit_logs')
    op.drop_table('platform_audit_logs')
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_index(op.f('ix_platform_roles_name'), table_name='platform_roles')
    op.drop_table('platform_roles')
    op.drop_index(op.f('ix_platform_permissions_resource'), table_name='platform_permissions')
    op.drop_index(op.f('ix_platform_permissions_name'), table_name='platform_permissions')
    op.drop_index(op.f('ix_platform_permissions_action'), table_name='platform_permissions')
    op.drop_table('platform_permissions')
    # ### end Alembic commands ###
