"""change endpoint_devices assigned_to FK to users

Revision ID: b2e8ab31843a
Revises: 6c12b4a43d2f
Create Date: 2026-06-23 14:29:20.382550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e8ab31843a'
down_revision: Union[str, None] = '6c12b4a43d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('endpoint_devices_assigned_to_fkey', 'endpoint_devices', type_='foreignkey')
    op.create_foreign_key(None, 'endpoint_devices', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'endpoint_devices', type_='foreignkey')
    op.create_foreign_key('endpoint_devices_assigned_to_fkey', 'endpoint_devices', 'people_assets', ['assigned_to'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
