"""add_org_external_id_nullable

Revision ID: b7ea051b0d4a
Revises: 46df84012637
Create Date: 2026-06-05 14:54:40.437958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ea051b0d4a'
down_revision: Union[str, None] = '46df84012637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('external_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_organizations_external_id'), 'organizations', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_external_id'), table_name='organizations')
    op.drop_column('organizations', 'external_id')
    # ### end Alembic commands ###
