"""add_compliance_framework_management

Revision ID: f1414d82f9e0
Revises: b079f4c7ddd0
Create Date: 2026-06-08 09:01:03.836556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1414d82f9e0'
down_revision: Union[str, None] = 'b079f4c7ddd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_name'), 'frameworks', ['name'], unique=True)
    op.create_table('controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('compliant', 'non_compliant', 'in_progress', 'not_applicable', name='compliance_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_code'), 'controls', ['code'], unique=False)
    op.create_index(op.f('ix_controls_organization_id'), 'controls', ['organization_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_code'), 'requirements', ['code'], unique=False)
    op.create_index(op.f('ix_requirements_framework_id'), 'requirements', ['framework_id'], unique=False)
    op.create_table('control_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_mappings_control_id'), 'control_mappings', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_mappings_requirement_id'), 'control_mappings', ['requirement_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_control_id'), 'evidence', ['control_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_control_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_control_mappings_requirement_id'), table_name='control_mappings')
    op.drop_index(op.f('ix_control_mappings_control_id'), table_name='control_mappings')
    op.drop_table('control_mappings')
    op.drop_index(op.f('ix_requirements_framework_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_code'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_controls_organization_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_code'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_frameworks_name'), table_name='frameworks')
    op.drop_table('frameworks')
    # ### end Alembic commands ###
