"""add compute_assets table

Revision ID: f2c099daca39
Revises: 8de032e8dc66
Create Date: 2026-06-23 17:52:08.675171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c099daca39'
down_revision: Union[str, None] = '8de032e8dc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('provisioned_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compute_assets_asset_type'), 'compute_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_compute_assets_organization_id'), 'compute_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compute_assets_owner_id'), 'compute_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_compute_assets_status'), 'compute_assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compute_assets_status'), table_name='compute_assets')
    op.drop_index(op.f('ix_compute_assets_owner_id'), table_name='compute_assets')
    op.drop_index(op.f('ix_compute_assets_organization_id'), table_name='compute_assets')
    op.drop_index(op.f('ix_compute_assets_asset_type'), table_name='compute_assets')
    op.drop_table('compute_assets')
    # ### end Alembic commands ###
